IO module: add.json.support to configuration package
optimad/bitpit pull request #199
Opened 2021-06-21 11:24 UTC by roccoarpa

The following pull adds into IO::ConfigParser class the possibility to parse/write json formatted dictionaries. 
Data structure and interfaces of the Config/Config parser classes are the same as before, XML parsing/writing functionalities are also preserved and totally independent from the new json add-on.

RapidJSON external library is used. The external dep is handled silently during bitpit compiling, applying the following the scheme:
1) RapidJSON is found quietly on the system
2) if it's found, set to true a bitpit internal-only precomp variable HAS_RAPIDJSON_LIB and compile with json support.
3) otherwise set to false HAS_RAPIDJSON_LIB, and ignore JSON related code.
In any case, XML support is always guaranteed.
Dictionary format conversion is possible too (parse a JSON file and write it in XML and vice-versa).

In order to comply with the IO::Config tree structure, bitpit JSON parsing  is limited only to arrays of JSON objects. Arrays of doubles, integers, booleans, string or null are not supported, and any attempt to parse them trigger an error.  

A test_io_00007 is added to check json parsing and writing. 

Tested on gcc 4.8 Linux  and MinGW Win10 gcc-10

2021-06-27 19:59 UTC, andrea-iob requested changes
I've added some fixup commits, mainly changes to adapt the coding style to the one used in bitpit. I've also modified the functions that read/write JSON values, they are now more similar to each other and more similar to what is done in the XML configuration. Finally, I moved the read/write buffers into the heap. 

I would like to request two changes:
 - would it be possible to use a broader check for the required version (e.g., 1.1 or even 1)?
 - could you modify the .travis.yml file and add rapidJSON to the packages installed in the test environment?

2021-06-28 10:32 UTC, roccoarpa commented
To address requests: 
   1) There's practically a unique stable version 1.1.0 for now and almost all major linux distros support 1.1.0 in their repo packages. Older versions seems outdated.   
   2) for Ubuntu platforms there is a rapidjson-dev package available.  rapidjson v.1.1.0 is supported regularly from Ubuntu 18.04 Bionic up to 21.04. Current Xenial (16.04) in use on travis has the package, but it seems an outdated version. Maybe it will be better to insert the rapidjson testing as soon as the travis reference platform is upgraded.

2021-06-28 13:12 UTC, andrea-iob approved these changes

2021-06-30 05:42 UTC, andrea-iob commented
When no RapidJSON was found on the system, the test was exiting without calling MPI_finalize. This made the test fail on Travis. I've modified the test to call MPI finalize also when RapidJSON is not found.

2021-06-30 05:42 UTC, merged