patchkernel: fix evaluation of partitioning information
optimad/bitpit pull request #312
Opened 2022-05-31 14:28 UTC by andrea-iob

The assert in Patchkernel::getOwner was wrong, additionally partitioning information status should be tracked also when there is only one processor.

2022-05-31 15:52 UTC, roccoarpa requested changes

2022-05-31 15:52 UTC, roccoarpa commented on src/patchkernel/patch_kernel_parallel.cpp
> +	assert(!arePartitioningInfoDirty(false));
Another booby trap. If you're working  MPI with 1 processor, isPartitioned is always true (that means communicator is always set by class constructor), arePartitioningInfoDirty return always true. See below

2022-05-31 15:52 UTC, roccoarpa commented on src/patchkernel/patch_kernel_parallel.cpp
> -		return false;
This was the failsafe for the assert failing before.

2022-05-31 16:31 UTC, roccoarpa approved these changes

2022-06-01 08:01 UTC, kgkara approved these changes

2022-06-07 18:24 UTC, merged