Add Levelset RBF generator
optimad/bitpit pull request #352
Opened 2022-10-19 19:11 UTC by oguevremont

- Add a RBF generator for the signed distance field from STL files
- Modify of the RBFKernel to allow variable support radii

2022-11-15 10:08 UTC, kgkara commented
Hello @oguevremont. Thank you very much for your contributions. To be able to merge them on the bitpit master, it will be needed to remove the dependencies on the Eigen library. So, you could use instead the infrastructure provided by bitpit, in the SystemSolver class. After that, we will return with the final review on this pull request.

2022-11-17 19:17 UTC, oguevremont commented
Hello @kgkara. Thank you for the tip. I have removed the dependency to Eigen as suggested and used SystemSolver. The PR is ready for review. I can squish all the commits once the review process is done.

2022-12-12 16:19 UTC, kgkara requested changes
Hello @oguevremont, thanks a lot for your contributions, they seem to be quite useful. There are some things that need to be addressed, as pointed out by the comments. Please feel free to ask for clarifications, if needed.

2022-12-19 16:00 UTC, oguevremont commented
Hello @kgkara, thank you for the review and for your time. I have addressed the comments so that the format is more in line with the other examples. The executable RBF_example_00001 can now be run, without arguments (default) or with arguments. The default STL file to be used is cube.stl in the levelset integration tests.

2023-01-09 10:31 UTC, kgkara requested changes
@oguevremont Thank you very much for your time. For me this pull request is practically ready, I just have two tiny comments. After these 2 tiny fixes, I will approve this pull request and after the review of @andrea-iob, we can merge it to the master.

2023-01-09 10:31 UTC, kgkara commented on examples/RBF_example_00001.cpp
> +*/
Could you please explain what the RBF_cube* {input and vtu} output files are?

2023-01-09 10:31 UTC, kgkara commented on examples/RBF_example_00001.cpp
> +    ofstream fw("RBF_" + filename + ".input", std::ofstream::ate);
Maybe "output" here is better than "input"?

2023-01-09 21:35 UTC, oguevremont commented
> @oguevremont Thank you very much for your time. For me this pull request is practically ready, I just have two tiny comments. After these 2 tiny fixes, I will approve this pull request and after the review of @andrea-iob, we can merge it to the master.

Thanks for the comments! I addressed them

2023-01-10 08:34 UTC, kgkara approved these changes

2023-01-10 08:35 UTC, kgkara commented
> > @oguevremont Thank you very much for your time. For me this pull request is practically ready, I just have two tiny comments. After these 2 tiny fixes, I will approve this pull request and after the review of @andrea-iob, we can merge it to the master.
> 
> Thanks for the comments! I addressed them

Thank you very much for the changes and your overall contributions.

2023-01-10 20:55 UTC, oguevremont commented
> To speedup the review process I created a new branch with some suggested changes ("ai.RBF.levelset.generator"). If the changes are fine with you you can reset your branch on my updated branch and then we can proceed with the merge.
> 
> Here the changes I've made:
> 
> * I've split the changes in self contained commits;
> * support radius is always get through getSupportRadius function (I'm assuming that the optimization of evaluating the inverse of the radius outside the loop is not critical in terms of performances);
> * evaluateBasisPair was moved inside the RBFKernel object and renamed to evalBasisPair for consistency with other methods;
> * the functon getWeights now return a constant reference to the weights;
> * I've fixed some warnings in the example;
> * I've copied the STL needed to run the example in the same directory of the executable;
> * I did some changes to the code style to make it consistent with the existing code.

These changes make sense to me! For future contributions I'll be careful to follow the coding style better, thanks for the input
I did the reset of my branch, so you can merge when you'd like

2023-01-12 08:50 UTC, andrea-iob approved these changes

2023-01-12 08:52 UTC, merged