reconstruction: correct the computation of derivatives
optimad/bitpit pull request #395
Opened 2023-05-19 13:48 UTC by ksamouchos

Function "computeDerivatives" evaluates the gradient along the given normal direction similarly to function "computeGradients". However, when dimensions are zero, computeDerivatives throws a segmentation error, while computeGradients returns a zero value. This pull-request modifies computeDerivatives to be in accordance with computeGradients.

2023-05-19 13:55 UTC, andrea-iob commented
Can you remind me what m_dimensions is?

2023-05-19 14:18 UTC, andrea-iob commented
In bitpit the commits should have the format "module_name: commit message".

2023-05-19 14:33 UTC, ksamouchos commented
> 

Done!

2023-05-19 14:33 UTC, ksamouchos commented
> In bitpit the commits should have the format "module_name: commit message".

Done!

2023-05-22 06:54 UTC, andrea-iob requested changes
This only fixes the case when degree equal to one. The same function will fail some lines below if the degree is greater than one.

I've added a check on the number of dimensions in all functions that evaluates derivatives and values.

2023-06-19 12:52 UTC, ksamouchos commented
I incorporated changes recommended by @andrea-iob.

2023-06-19 12:57 UTC, andrea-iob approved these changes

2023-06-19 13:21 UTC, merged