Third parties
optimad/bitpit pull request #401
Opened 2023-06-07 14:57 UTC by haysam

THIRPARTIES.md contains a lot of third party components and their licenses to scope with inherited license obligations

2023-06-08 09:04 UTC, edoardolombardi commented
> bitpit is not redistributing (nor installing) any of these libraries.
> 
> Also, what if someone downloads bitpit and links it against OpenBLAS, or ATLAS or MKL? Should we include the licenses of all possible BLAS implementations? The same applies to MPI (which seems missing from the list) and to METIS (one can use SCOTCH instead of METIS).
> 
> I mean, we can include the file if it is needed by the GDPR, I'm just wondering how we can include the licenses of all possible third party libraries bitpit can be linked against (bitpit needs the glibc library, should we include also the license of that library?).

I agree. If we don't redistribute libraries with bitpit we don't need third parties licenses. We could update the required dependencies in [INSTALL.md](https://github.com/optimad/bitpit/blob/master/INSTALL.md) if needed (for instance, boost and rapidjson [both optionals] seem missing).

2023-06-08 15:43 UTC, marcocisternino commented on THIRDPARTIES.md
> +RAPIDJASON
RAPIDJSON!!!

2023-06-08 15:47 UTC, marcocisternino requested changes
What about MPI?

2023-06-09 06:57 UTC, andrea-iob commented
- Fixed some typos
- Added Open MPI
- Re-formatted the text to make it prettier
- Sorted the software in alphabetic order
- Canceled the CI tests (we can merge this pull request without running the tests)

2023-06-09 06:57 UTC, andrea-iob approved these changes

2023-06-09 12:20 UTC, marcocisternino approved these changes

2023-06-09 12:21 UTC, merged